version: "3.7"

services:
  server:
    container_name: server
    build:
      context: server
    volumes:
      - ./server:/server
      - ./client:/client
    ports: ["8000:8000"]
  client:
    container_name: client
    build:
      context: client
    volumes:
      - ./client:/client
    ports: ["80:3000"]
